apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q0qn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-q0qn@sha256:2f380bed2d63655f44ecfd232a518f5f6e21c6a5bf81081a7af5998c8f7a52ff
        name: my-nodejs
        resources: {}
status: {}
